
export const SELECT_ORDER = 'SELECT_ORDER';

export const SELECT_USER = 'SELECT_USER';
export const SELECT_TEMP_USER = 'SELECT_TEMP_USER';
export const SELECT_USER_CONFIG = 'SELECT_USER_CONFIG';

export const SELECT_MILL = 'SELECT_MILL';
export const SET_SEARCH_TERM='SET_SEARCH_TERM';

export const FETCH_TRADER_DATA_START = 'FETCH_TRADER_DATA_START';
export const FETCH_TRADER_DATA_SUCCESS = 'FETCH_TRADER_DATA_SUCCESS';
export const FETCH_TRADER_DATA_FAILURE = 'FETCH_TRADER_DATA_FAILURE';


export const STATE_REFRESH = 'STATE_REFRESH';


